version: '3'

services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3003:3000
    links:
      - database
      - redis
    volumes:
      - .:/app
    environment: &app_environment
      DATABASE_URL: postgres://postgres@database:5432/nemu_development?pool=25&encoding=unicode&schema_search_path=public
      REDIS_URL: redis://redis:6379

      # Enable the byebug debugging server - this can be overriden
      # from the command line:
      ENABLE_DEBUG_SERVER: 'true'

      # Run the app in the 'development' environment:
      RACK_ENV: development
      RAILS_ENV: development
    env_file:
      - ./.env.development

  worker:
    <<: *app_base
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  database:
    image: postgres:9.4-alpine
    ports:
      - 5432

  redis:
    image: redis:3.0.7-alpine
    ports:
      - 6379

  mailcatcher:
    image: voizzzzzz/mailcatcher-alpine
    ports:
      - 1080:1080