export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const SIGNED_OUT = 'SIGNED_OUT'

export const RECEIVE_ALL_EVENTS = 'RECEIVE_ALL_EVENTS'
export const RECEIVE_EVENT = 'RECEIVE_EVENT'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const SET_CURRENT_EVENT_ID = 'SET_CURRENT_EVENT_ID'
export const EVENT_CREATED = 'EVENT_CREATED'
export const UPDATE_ALL_EVENTS_LOADING = 'UPDATE_ALL_EVENTS_LOADING'
export const SET_IS_LOADING_CURRENT_EVENT = 'SET_IS_LOADING_CURRENT_EVENT'
export const SET_CREATE_EVENT_ERRORS = 'SET_CREATE_EVENT_ERRORS'
export const SET_IS_SAVING_EVENT = 'SET_IS_SAVING_EVENT'

export const CHANGE_NEW_EVENT_FORM_OPEN_STATE = 'CHANGE_NEW_EVENT_FORM_OPEN_STATE'

