export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const SIGNED_OUT = 'SIGNED_OUT'

export const RECEIVE_ALL_EVENTS = 'RECEIVE_ALL_EVENTS'
export const RECEIVE_EVENT = 'RECEIVE_EVENT'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const SET_CURRENT_EVENT_ID = 'SET_CURRENT_EVENT_ID'
export const EVENT_CREATED = 'EVENT_CREATED'
export const UPDATE_ALL_EVENTS_LOADING = 'UPDATE_ALL_EVENTS_LOADING'
export const SET_IS_LOADING_CURRENT_EVENT = 'SET_IS_LOADING_CURRENT_EVENT'
export const SET_CREATE_EVENT_ERRORS = 'SET_CREATE_EVENT_ERRORS'
export const SET_IS_SAVING_EVENT = 'SET_IS_SAVING_EVENT'
export const UPDATE_EVENT_BANDS_LOADING = 'UPDATE_EVENT_BANDS_LOADING'
export const CLEAR_EVENT_BANDS = 'CLEAR_EVENT_BANDS'
export const RECEIVE_EVENT_BANDS = 'RECEIVE_EVENT_BANDS'

export const CHANGE_NEW_EVENT_FORM_OPEN_STATE = 'CHANGE_NEW_EVENT_FORM_OPEN_STATE'

