export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const SIGNED_OUT = 'SIGNED_OUT'

export const RECEIVE_ALL_EVENTS = 'RECEIVE_ALL_EVENTS'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const UPDATE_ALL_EVENTS_LOADING = 'UPDATE_ALL_EVENTS_LOADING'

